name: quantum_wave_lab_flutter
description: "QT Lab: An interactive quantum mechanics simulator built with Flutter and Material 3."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#080B13"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  monochrome: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
